### ISSUE TITLE
Aggiornamento testi

### ISSUE THREAD

**Issue by Rankoll** [YoRHa-2G/YoRHa-2G#2]
̷-̷D̷a̷ ̷m̷o̷b̷i̷l̷e̷ ̷"̷C̷h̷i̷ ̷s̷o̷n̷o̷"̷ ̷n̷o̷n̷ ̷v̷i̷e̷n̷e̷ ̷t̷r̷a̷d̷o̷t̷t̷o̷ ̷n̷e̷ ̷s̷o̷t̷t̷o̷ ̷n̷e̷ ̷s̷o̷p̷r̷a̷
̷-̷A̷n̷c̷o̷r̷a̷ ̷d̷a̷ ̷i̷n̷s̷e̷r̷i̷r̷e̷ ̷l̷a̷ ̷s̷c̷r̷i̷t̷t̷a̷ ̷e̷a̷s̷t̷e̷r̷ ̷e̷g̷g̷
̷-̷F̷*̷ ̷t̷u̷t̷t̷o̷ ̷s̷o̷t̷t̷o̷ ̷c̷o̷l̷l̷a̷b̷o̷r̷a̷z̷i̷o̷n̷i̷ ̷f̷a̷r̷ ̷c̷o̷m̷p̷a̷r̷i̷r̷e̷ ̷a̷n̷c̷h̷e̷ ̷i̷ ̷r̷i̷n̷g̷r̷a̷z̷i̷a̷m̷e̷n̷t̷i̷ ̷e̷ ̷c̷e̷ ̷l̷i̷ ̷l̷e̷v̷i̷a̷m̷o̷ ̷d̷a̷ ̷a̷v̷a̷n̷t̷i̷
-Aumentare le grandezze dei font in generale dal sito mobile
-Aumentare la grandezza delle immagini nel sito mobile (larghe poco meno del div in cui sono contenute nella sezione dedicata)
 ̷-̷C̷r̷e̷d̷i̷t̷s̷ ̷h̷a̷ ̷l̷'̷e̷l̷e̷n̷c̷o̷ ̷p̷u̷n̷t̷a̷t̷o̷ ̷"̷c̷e̷n̷t̷r̷a̷t̷o̷"̷ ̷q̷u̷a̷n̷d̷o̷ ̷d̷o̷v̷r̷e̷b̷b̷e̷ ̷s̷t̷a̷r̷e̷ ̷a̷ ̷s̷i̷n̷i̷s̷t̷r̷a̷

**Comment by YoHRa2G** [comment]
Update:
-Da mobile "Chi sono" non viene tradotto ne sotto ne sopra
-Ancora da inserire la scritta easter egg
-F* tutto sotto collaborazioni far comparire anche i ringraziamenti e ce li leviamo da avanti
-Aumentare le grandezze dei font in generale dal sito mobile
-Aumentare la grandezza delle immagini nel sito mobile (larghe poco meno del div in cui sono contenute nella sezione dedicata)
